package client.GUI;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author pro
 */
public class ChatRoomGUI extends javax.swing.JFrame {

    private String ctid;
    private GUIManager manager;

//    private BlockingDeque<String> responseQueue=new LinkedBlockingDeque<String>();

//    public BlockingDeque<String> getResponseQueue() {
//        return responseQueue;
//    }

//    public void setResponseQueue(BlockingDeque<String> responseQueue) {
//        this.responseQueue = responseQueue;
//    }

    public ChatRoomGUI(GUIManager manager) {
        this.manager=manager;
    }

    /**
     * Creates new form ChatRoomGUI
     */
    public ChatRoomGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textToSend = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        onlinePeople = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        sendButtom = new javax.swing.JButton();
        exitChatRoomButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setTitle("frame11");

        setBounds(new java.awt.Rectangle(300, 200, 500, 500));

        infoArea.setEditable(false);
        infoArea.setColumns(20);
        infoArea.setRows(5);
        jScrollPane1.setViewportView(infoArea);

        textToSend.setColumns(20);
        textToSend.setRows(5);
        jScrollPane2.setViewportView(textToSend);

        onlinePeople.setEditable(false);
        onlinePeople.setColumns(5);
        onlinePeople.setRows(5);
        jScrollPane3.setViewportView(onlinePeople);

        jLabel1.setText("     当前在线");

        sendButtom.setText("发送");
        sendButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtomActionPerformed(evt);
            }
        });

        exitChatRoomButton.setText("离开聊天室");
        exitChatRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitChatRoomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sendButtom, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addComponent(exitChatRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(sendButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(exitChatRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void sendButtomActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String header="message:12n!\0"+manager.getUid()+"&"+ctid+"\0";
        String info=header+manager.getNickname()+": "+textToSend.getText();
        manager.getClientSocket().write(info);
        textToSend.setText("");
    }

    private void exitChatRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        String header="header:exit room!\0"+manager.getUid()+"&"+ctid;
        manager.getClientSocket().write(header);
//        manager.getLoginAtferMainGUI().go();
    }

    public void go(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        initComponents();
        setTitle(manager.getChatRoomGUI(ctid).getName());
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatRoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatRoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatRoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatRoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    public void callback(String result){
        if (result.toString().trim().isEmpty()) {
            String message = "server is close,please try login again";
            System.out.println(message);
            setVisible(false);
            manager.getErrorGUI().showJ();
            return ;
        }
        //去掉请求头和参数
        String message =result.substring(result.indexOf("\n")+1);
        message=message.substring(message.indexOf("\n")+1);
        infoArea.append(message);
    }

    public void showPeople(String[] result){
        StringBuilder sb=new StringBuilder();
        for (int i = 2; i <result.length ; i++) {
            sb.append(result[i]+"\n");
        }
        onlinePeople.setText(sb.toString());
    }

    public void showRecord(String result){
        String info=result.substring(result.indexOf("\n")+1);
        info=info.substring(info.indexOf("\n")+1);
        infoArea.append(info);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton exitChatRoomButton;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea onlinePeople;
    private javax.swing.JButton sendButtom;
    private javax.swing.JTextArea textToSend;
    // End of variables declaration


    public String getCtid() {
        return ctid;
    }

    public void setCtid(String ctid) {
        this.ctid = ctid;
    }
}
