package client.GUI;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import client.socket.ClientSocket;
import utils.DateUtil;

import java.io.*;
import java.util.ArrayList;

/**
 *
 * @author pro
 */
public class ChatRoomGUI extends javax.swing.JFrame {

    private GUIManager manager;


    public ChatRoomGUI(GUIManager manager) {
        this.manager=manager;
        initComponents();
    }

    /**
     * Creates new form ChatRoomGUI
     */
    public ChatRoomGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textToSend = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        onlinePeople = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        sendButtom = new javax.swing.JButton();
        exitChatRoomButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setBounds(new java.awt.Rectangle(300, 200, 500, 500));

        infoArea.setEditable(false);
        infoArea.setColumns(20);
        infoArea.setRows(5);
        jScrollPane1.setViewportView(infoArea);

        textToSend.setColumns(20);
        textToSend.setRows(5);
        jScrollPane2.setViewportView(textToSend);

        onlinePeople.setEditable(false);
        onlinePeople.setColumns(5);
        onlinePeople.setRows(5);
        jScrollPane3.setViewportView(onlinePeople);

        jLabel1.setText("     当前在线");

        sendButtom.setText("发送");
        sendButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtomActionPerformed(evt);
            }
        });

        exitChatRoomButton.setText("离开聊天室");
        exitChatRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitChatRoomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sendButtom, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addComponent(exitChatRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(sendButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(exitChatRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void sendButtomActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String header="message:12n!\n";
        String info=textToSend.getText();
        manager.getClientSocket().write(info);
        textToSend.setText("");
    }

    private void exitChatRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        manager.getLoginAtferMainGUI().go();
    }

    public void go(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatRoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatRoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatRoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatRoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
        new Thread(new Runnable() {
            @Override
            public void run() {
                int i=0;
//                ArrayList<Byte> list=new ArrayList<Byte>(1024);
                while(true) {
//                    list.clear();
//                    InputStream in = ClientSocket.getSocket().getInputStream();
//                    for (int i = in.read(); i >0; i = in.read()) {
//                        char c = (char) i;
//                        if (c == '\0')
//                            break;
////                            sb.append(c);
//                        list.add((byte) c);
//                    }
//                    //转码
//                    byte[] bytes=new byte[list.size()];
//                    for (int i = 0; i <bytes.length ; i++)
//                        bytes[i]=list.get(i);
                    String sb = manager.getClientSocket().read();
                    System.out.println("执行了" + i + "次");
                    i++;
                    if (sb.toString().trim().isEmpty()) {
                        String message = "server is close,please try login again";
                        System.out.println(message);
                        setVisible(false);
                        manager.getErrorGUI().showJ();
                        break;
                    }
                    String message = null;
                    try {
                        message = DateUtil.getNowDate() + "\n" + new String(sb.toString().getBytes(), "UTF-8") + "\n";
                    } catch (UnsupportedEncodingException e) {
                        e.printStackTrace();
                    }
//                        System.out.println(sb.toString());
                    infoArea.append(message);

                }
            }
        }).start();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton exitChatRoomButton;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea onlinePeople;
    private javax.swing.JButton sendButtom;
    private javax.swing.JTextArea textToSend;
    // End of variables declaration


}
